# Generated by Django 3.2.23 on 2025-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_featuredproductline_historicalfeaturedproductline'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproductline',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfeaturedproductline',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
