# Generated by Django 3.2.23 on 2025-09-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historicalproductvariant_historicalvariantfilter_productvariant_variantfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductvariant',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='extra_data',
        ),
    ]
