# Generated by Django 3.2.23 on 2025-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcartitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
