# Generated by Django 3.2.23 on 2025-09-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20250919_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcartitem',
            name='user',
        ),
    ]
