# Generated by Django 3.2.23 on 2025-09-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250919_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluseraddress',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
