# Generated by Django 3.2.23 on 2025-09-20 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20250919_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
